version: '2'
services:
  zk-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-1
    ports:
      - "12181:12181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:12888:13888;zk-2:22888:23888;zk-3:32888:33888

  zk-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-2
    ports:
      - "22181:22181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:12888:13888;zk-2:22888:23888;zk-3:32888:33888

  zk-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-3
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:12888:13888;zk-2:22888:23888;zk-3:32888:33888

  kfk-1:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-1
    ports:
      - "19092:19092"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-1:12181,zk-2:12181,zk-3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-1:19092
 
  kfk-2:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-2
    ports:
      - "29092:29092"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk-1:12181,zk-2:12181,zk-3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-2:29092
 
  kfk-3:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-3
    ports:
      - "39092:39092"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk-1:12181,zk-2:12181,zk-3:12181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-3:39092
