version: '3'
services:
  produce:
    build: ./produce
    container_name: produce
    ports: 
      - "9000:9000"
    environment:
      LISTEN_ADDRESS: '0.0.0.0:9000'
      KAFKA_BROKERS: 'kfk1:19092,kfk2:29092,kfk3:39092'
      KAFKA_TOPIC: 'foo'

  consume1:
    build: ./consume
    container_name: consume1
    environment:
      KAFKA_BROKERS: 'kfk1:19092,kfk2:29092,kfk3:39092'
      KAFKA_CONSUMER_GROUP_ID: 'consumer-group'
      KAFKA_TOPIC: 'foo'

  consume2:
    build: ./consume
    container_name: consume2
    environment:
      KAFKA_BROKERS: 'kfk1:19092,kfk2:29092,kfk3:39092'
      KAFKA_CONSUMER_GROUP_ID: 'consumer-group'
      KAFKA_TOPIC: 'foo'

networks:
  default:
    external:
      name: kafka_default